name: Docker

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        PHP_VERSION: [lsphp73, lsphp74]
        TAG: [latest,'']
    steps:
      - run: echo ${{github.ref}}
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd ${FOLDER}; ls 
          docker-compose -v
          bash build.sh --ols ${OLS_VERSION} --php ${{ matrix.PHP_VERSION }} --tag ${{ TAG }}
          docker image ls
        env: 
          FOLDER: template 
          OLS_VERSION: 1.6.19
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  