name: Docker

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        PHP_VERSION: [lsphp73, lsphp74]
        TAG: [latest,'']
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd ${FOLDER}; ls 
          docker ps
          which docker-compose 
          bash build.sh -h
          bash build.sh --ols 1.6.20 --php lsphp74
          docker image ls
        env: 
          FOLDER: template 
          OLS_VERSION: 1.6.19
  